"""initial_schema

Revision ID: 6ed570034525
Revises: 
Create Date: 2026-07-23 19:53:13.448611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ed570034525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_items', 'menu_items', ['menu_item_id'], ['id'])
    op.add_column('orders', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('preparing_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_by', sa.Enum('USER', 'ADMIN', 'SYSTEM', name='cancelledby'), nullable=True))
    op.add_column('orders', sa.Column('pickup_otp_hash', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('otp_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('otp_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'otp_verified_at')
    op.drop_column('orders', 'otp_generated_at')
    op.drop_column('orders', 'pickup_otp_hash')
    op.drop_column('orders', 'cancelled_by')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'completed_at')
    op.drop_column('orders', 'ready_at')
    op.drop_column('orders', 'preparing_at')
    op.drop_column('orders', 'accepted_at')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    # ### end Alembic commands ###
