"""add_stall_id_and_profile_complete_to_user_stall_id_to_order

Revision ID: 89881578276e
Revises: b82ce008ef79
Create Date: 2026-07-25 12:05:35.597056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89881578276e'
down_revision: Union[str, Sequence[str], None] = 'b82ce008ef79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('stall_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_stall_id'), 'orders', ['stall_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'food_stalls', ['stall_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('stall_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('profile_complete', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_unique_constraint(None, 'users', ['stall_id'])
    op.create_foreign_key(None, 'users', 'food_stalls', ['stall_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'profile_complete')
    op.drop_column('users', 'stall_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_stall_id'), table_name='orders')
    op.drop_column('orders', 'stall_id')
    # ### end Alembic commands ###
