"""add current_menu_page to user_sessions

Revision ID: a3784be1f9ec
Revises: 764288649863
Create Date: 2026-07-24 20:08:46.766055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3784be1f9ec'
down_revision: Union[str, Sequence[str], None] = '764288649863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "user_sessions",
        sa.Column(
            "current_menu_page",
            sa.Integer(),
            nullable=False,
            server_default="1",
        ),
    )

    op.alter_column(
        "user_sessions",
        "current_menu_page",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sessions', 'current_menu_page')
    # ### end Alembic commands ###
