"""add opening and closing time to stalls

Revision ID: b82ce008ef79
Revises: 995a125cbac8
Create Date: 2026-07-25 11:32:55.321116

"""
from typing import Sequence, Union
from sqlalchemy import text
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82ce008ef79'
down_revision: Union[str, Sequence[str], None] = '995a125cbac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Add the new columns as nullable first
    op.add_column(
        "food_stalls",
        sa.Column(
            "opening_time",
            sa.Time(),
            nullable=True,
        ),
    )

    op.add_column(
        "food_stalls",
        sa.Column(
            "closing_time",
            sa.Time(),
            nullable=True,
        ),
    )

    # Give existing stalls default operating hours
    op.execute(
        text(
            """
            UPDATE food_stalls
            SET opening_time = '09:00:00',
                closing_time = '18:00:00'
            """
        )
    )

    # Make the columns required
    op.alter_column(
        "food_stalls",
        "opening_time",
        nullable=False,
    )

    op.alter_column(
        "food_stalls",
        "closing_time",
        nullable=False,
    )

    # Remove the old column
    op.drop_column(
        "food_stalls",
        "is_open",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_stalls', sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('food_stalls', 'closing_time')
    op.drop_column('food_stalls', 'opening_time')
    # ### end Alembic commands ###
