"""add user sessions table

Revision ID: deddcec3b446
Revises: 6ed570034525
Create Date: 2026-07-24 15:29:13.802066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deddcec3b446'
down_revision: Union[str, Sequence[str], None] = '6ed570034525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('INITIAL', 'WAITING_FOR_NAME', 'WAITING_FOR_REGISTRATION', 'SELECTING_STALL', 'VIEWING_MENU', 'BUILDING_CART', 'SELECTING_SLOT', 'CONFIRMING_ORDER', 'ORDER_COMPLETE', name='chatstate'), nullable=False),
    sa.Column('selected_stall_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['selected_stall_id'], ['food_stalls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.alter_column('users', 'registration_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'registration_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
