from enum import Enum


class ChatState(str, Enum):
    INITIAL = "INITIAL"

    WAITING_FOR_NAME = "WAITING_FOR_NAME"
    WAITING_FOR_REGISTRATION = "WAITING_FOR_REGISTRATION"

    SELECTING_STALL = "SELECTING_STALL"
    VIEWING_MENU = "VIEWING_MENU"

    BUILDING_CART = "BUILDING_CART"

    SELECTING_SLOT = "SELECTING_SLOT"

    CONFIRMING_ORDER = "CONFIRMING_ORDER"

    ORDER_COMPLETE = "ORDER_COMPLETE"
    